services:
  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: always
    volumes:
      - nodered_data:/data
    networks:
      - monitor-net
    ports:
      - "1880:1880"

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin1234
      DOCKER_INFLUXDB_INIT_ORG: main
      DOCKER_INFLUXDB_INIT_BUCKET: main
      DOCKER_INFLUXDB_INIT_RETENTION: 0
    networks:
      - monitor-net
    ports:
      - "8086:8086"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: administrator
      GF_SECURITY_ADMIN_PASSWORD: admini1234
      #GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
      # GF_SERVER_ROOT_URL: "/grafana/"
      GF_SERVER_ROOT_URL: "/"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    networks:
      - monitor-net
    depends_on:
      - influxdb
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - monitor-net

volumes:
  influxdb_data:
  grafana_data:
  nodered_data:

networks:
  monitor-net:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:db8::/64